(cl:in-package VehicleDataReader-msg)
(cl:export '(MESSAGEID-VAL
          MESSAGEID
          VEHICLESPEED-VAL
          VEHICLESPEED
          ENGINESPEED-VAL
          ENGINESPEED
          DRIVERDOOR_OPEN-VAL
          DRIVERDOOR_OPEN
          FRONTPASSENGERDOOR_OPEN-VAL
          FRONTPASSENGERDOOR_OPEN
          REARLEFTDOOR_OPEN-VAL
          REARLEFTDOOR_OPEN
          REARRIGHTDOOR_OPEN-VAL
          REARRIGHTDOOR_OPEN
          FRAMETICKCOUNTSYSREADTIME-VAL
          FRAMETICKCOUNTSYSREADTIME
))